name: Build .NET Project

# This workflow is used by services workfow for Setup and Net building
on:
  workflow_call:
    inputs:
      SOLUTION_PATH:
        description: 'The path to the solution file'
        required: true
        type: string
      OUTPUT_FILENAME:
        description: 'Name of the outputfile'
        required: false
        type: string
        default: 'Build-Output'
      CONFIGURATION:
        description: 'Build configuration (e.g., Release or Debug)'
        required: false
        type: string
        default: 'Release'
      PLATFORM:
        description: 'Target platform (e.g., win-x64, linux-x64)'
        required: false
        type: string
        default: 'win-x64'
      DOCKER_FILE_PATH:
        description: 'Docker file from service for docker operations'
        required: false
        type: string

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest]
    permissions:
      contents: write
      packages: write
      
    steps:
      - name: Debug Environment Variables
        run: env

      # 1. Repository auschecken
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Holt die gesamte Historie

      # 8. Projekt bauen
      #- name: Build the project
      #  run: dotnet build ${{ inputs.SOLUTION_PATH }} --configuration ${{ inputs.CONFIGURATION }}
      
      #commands or actions pipe | sytax
      # Log in to Docker Hub
      #- name: Log in to Docker Hub
      #  run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Log in to Docker Hub
      - name: Push to My Docker
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: santhucr7/net-core-test-app
          registry: docker.io
          tag: latest
          dockerfile: ${{ inputs.DOCKER_FILE_PATH }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 12. END
      - name: End Signed San
        run: echo "Success. End GitHub Actions"