name: Build-Test-Publish NET Project

on:
  workflow_call:
    inputs:
      SOLUTION_PATH:
        description: 'The path to the solution file'
        required: true
        type: string
      OUTPUT_FILENAME:
        description: 'Name of the outputfile'
        required: false
        type: string
        default: 'Build-Output'
      CONFIGURATION:
        description: 'Build configuration (e.g., Release or Debug)'
        required: false
        type: string
        default: 'Release'
      PLATFORM:
        description: 'Target platform (e.g., win-x64, linux-x64)'
        required: false
        type: string
        default: 'win-x64'
      TEST_PATH:
        description: 'The test csproj path'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build the project
        run: dotnet build ${{ inputs.SOLUTION_PATH }} --configuration ${{ inputs.CONFIGURATION }}

      - name: Run Tests
        run: dotnet test ${{ inputs.TEST_PATH }} --configuration ${{ inputs.CONFIGURATION }} --logger "trx;LogFileName=TestResults.trx"

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: TestResults.trx

      - name: Publish the project
        run: dotnet publish ${{ inputs.SOLUTION_PATH }} --configuration ${{ inputs.CONFIGURATION }} --runtime ${{ inputs.PLATFORM }} --output ./deploy --self-contained false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.OUTPUT_FILENAME }}
          path: ./deploy
